name: Bug report
description: Report an unexpected error, a crash, or an incorrect behavior
title: "ansible_role_name_here: short_desc_here"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        :wave:
        
        Thank you for taking the time to fill out this bug/issue report!

        Before raising a bug/issue, please read the documentation of the Ansible Role where the feature or enhancement is requested; such as [community.sap_install/roles/sap_hana_install/README](https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_hana_install/README.md)

  - type: dropdown
    id: role
    attributes:
      label: Ansible Role
      description: Which Ansible Role are you proposing a feature or enhancement for?
      options:
        - All
        - sap_anydb_install_oracle
        - sap_general_preconfigure
        - sap_ha_install_anydb_ibmdb2
        - sap_ha_install_hana_hsr
        - sap_ha_pacemaker_cluster
        - sap_hana_install
        - sap_hana_preconfigure
        - sap_hostagent
        - sap_install_media_detect
        - sap_maintain_etc_hosts
        - sap_netweaver_preconfigure
        - sap_storage_setup
        - sap_swpm
        - None of them (or I don't know)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: os-family
    attributes:
      label: OS Family
      description: Which OS are experiencing the issue with?
      options:
        - N/A
        - RHEL
        - SLES
      default: 0
    validations:
      required: true

  - type: textarea
    id: python-version
    attributes:
      label: Ansible Controller - Python version
      description: From wherever you execute Ansible, please provide the Python version being used
      placeholder: |
        python --version
        Python 3.12.0
    validations:
      required: true

  - type: textarea
    id: ansible-version
    attributes:
      label: Ansible-core version
      description: From wherever you execute Ansible, please provide the Ansible Core version being used
      placeholder: |
        ansible --version
        ansible [core 2.16.0]
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the bug. You can attach images (drag-and-drop) or log files as required.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Bug reproduction
      description: Please provide the steps you performed, so we can try to reproduce the problem you ran into
    validations:
      required: true

  - type: dropdown
    id: additional
    attributes:
      label: Additional information
      description: Do you intend to submit a **Pull Request** to solve this bug?
      options:
        - I will raise a Pull Request with the code fix
        - I am unable to contribute the fix
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Before submitting this request, please confirm
      options:
        - label: Yes, I read the documentation
          required: true
        - label: Yes, I checked if there was already a previous [GitHub Issue](https://github.com/sap-linuxlab/community.sap_install/issues?q=is%3Aissue%20) about this bug
          required: true

  - type: markdown
    attributes:
      value: |
        **Before submitting this report, I confirm:**
        
        - :white_check_mark: Yes, I read the documentation

        - :white_check_mark: Yes, I checked if there was already a previous [GitHub Issue](https://github.com/sap-linuxlab/community.sap_install/issues?q=is%3Aissue%20) about this bug
