name: Bug report
description: Report an unexpected error, a crash, or an incorrect behavior
title: "ansible_role_name_here: short_desc_here"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        :wave:
        
        Thank you for taking the time to fill out this bug/issue report!

        Before raising a bug/issue, please read the documentation of the Ansible Role where the feature or enhancement is requested; such as [community.sap_install/roles/sap_hana_install/README](https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_hana_install/README.md)

  - type: dropdown
    id: role
    attributes:
      label: Ansible Role
      description: Which Ansible Role are you proposing a feature or enhancement for?
      options:
        - All
        - sap_anydb_install_oracle
        - sap_general_preconfigure
        - sap_ha_install_anydb_ibmdb2
        - sap_ha_install_hana_hsr
        - sap_ha_pacemaker_cluster
        - sap_hana_install
        - sap_hana_preconfigure
        - sap_hostagent
        - sap_install_media_detect
        - sap_maintain_etc_hosts
        - sap_netweaver_preconfigure
        - sap_storage_setup
        - sap_swpm
        - None of them (or I don't know)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: os-family
    attributes:
      label: OS Family
      description: Which OS are experiencing the issue with?
      options:
        - N/A
        - RHEL
        - SLES
      default: 0
    validations:
      required: true

  - type: textarea
    id: python-version
    attributes:
      label: Ansible Controller - Python version
      description: From wherever you execute Ansible, please provide the Python version being used
      placeholder: |
        python --version
        Python 3.12.0
    validations:
      required: true

  - type: textarea
    id: ansible-version
    attributes:
      label: Ansible-core version
      description: From wherever you execute Ansible, please provide the Ansible Core version being used
      placeholder: |
        ansible --version
        ansible [core 2.16.0]
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce the bug
      description: Please provide a way for us to be able to reproduce the problem you ran into.
    validations:
      required: true

  - type: dropdown
    id: additional
    attributes:
      label: Additional information
      description: Do you intend to submit a **Pull Request** to solve this bug?
      options:
        - I can solve this bug
        - I can't solve this bug
    validations:
      required: true

  - type: textarea
    id: additional-duplicated-issue
    attributes:
      label: I've already checked for existing duplicated [issues](https://github.com/sap-linuxlab/community.sap_install/issues?q=is%3Aissue+label%3Abug).
      description: |
        Is there any related [issues](https://github.com/sap-linuxlab/community.sap_install/issues?q=is%3Aissue+label%3Abug) that you think is linked to this bug? 

        Add link to the issue or leave empty if there are none!
      placeholder: Issue duplicated

  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: I've read [the documentation](https://github.com/sap-linuxlab/community.sap_install/tree/main/docs#readme).
          required: true
