---
name: Feature request
description: Request a feature or enhancement to the Ansible Collection
title: "feat: ansible_role_name_here short_desc_here"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        :wave:
        
        Thank you for taking the time to fill out this feature request!

        Before raising a feature request, please read the documentation of the Ansible Role where the feature or enhancement is requested; such as [community.sap_install/roles/sap_hana_install/README](https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_hana_install/README.md)

  - type: dropdown
    id: role
    attributes:
      label: Ansible Role
      description: Which Ansible Role are you proposing a feature or enhancement for?
      options:
        - All
        - sap_anydb_install_oracle
        - sap_general_preconfigure
        - sap_ha_install_anydb_ibmdb2
        - sap_ha_install_hana_hsr
        - sap_ha_pacemaker_cluster
        - sap_hana_install
        - sap_hana_preconfigure
        - sap_hostagent
        - sap_install_media_detect
        - sap_maintain_etc_hosts
        - sap_netweaver_preconfigure
        - sap_storage_setup
        - sap_swpm
      default: 0
    validations:
      required: true

  - type: dropdown
    id: os-family
    attributes:
      label: OS Family
      description: Is feature or enhancement OS specific?
      options:
        - All
        - RHEL
        - SLES
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature/Enhancement request
      description: A clear and concise description of what will improve the Ansible Role; please include use cases for the desired final outcome.
      placeholder: |
        e.g. I believe [...] would help clarity to end-users during execution.

        e.g. I believe [...] is required to avoid [...] problem/s occuring.

        e.g. I believe [...] is missing according to [citation] SAP documentation.
    validations:
      required: true

  - type: dropdown
    id: additional
    attributes:
      label: Community participation
      description: Do you want to join our community and contribute/implement this feature yourself?
      options:
        - I can implement this feature
        - I can implement this feature, but need help as it is my first time contributing to open-source using git
        - I cannot implement this feature
    validations:
      required: true

  - type: textarea
    id: attempted-solution
    attributes:
      label: Optional - Attempted solutions or manual steps
      description: If you already have some Ansible code or manual steps (shell commands), please paste these below
      placeholder: |
        <paste example code here>
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <br/>
        
        **Before submitting this request, I confirm:**
        
        - :white_check_mark: Yes, I read the documentation
